ALTER TABLE work_tasks ADD COLUMN IF NOT EXISTS quality_score INTEGER;
ALTER TABLE work_tasks ADD COLUMN IF NOT EXISTS quality_status VARCHAR(30) NOT NULL DEFAULT 'NEEDS_REVIEW';
ALTER TABLE work_tasks ADD COLUMN IF NOT EXISTS quality_report VARCHAR(8000) NOT NULL DEFAULT '';
